import AppKit
import Foundation

/// Watches the system pasteboard and reports new content.
///
/// macOS has no "pasteboard changed" notification, so the only option is to
/// poll `changeCount`, which is cheap: reading the payload happens only on the
/// ticks where the count actually moved.
@MainActor
public final class ClipboardMonitor {

    /// Markers other apps set to say "do not record this". Password managers
    /// use ConcealedType, so honouring these keeps secrets out of the history.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public var onCapture: ((ClipboardItem) -> Void)?

    public private(set) var isRunning = false

    private let pasteboard: NSPasteboard
    private let persistence: PersistenceProtocol?
    private let interval: TimeInterval
    private var timer: Timer?
    private var lastChangeCount: Int

    public init(
        pasteboard: NSPasteboard = .general,
        persistence: PersistenceProtocol? = nil,
        interval: TimeInterval = 0.4
    ) {
        self.pasteboard = pasteboard
        self.persistence = persistence
        self.interval = interval
        self.lastChangeCount = pasteboard.changeCount
    }

    deinit { timer?.invalidate() }

    public func start() {
        guard !isRunning else { return }
        isRunning = true

        // Whatever is on the pasteboard right now predates monitoring.
        lastChangeCount = pasteboard.changeCount

        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // .common so polling continues while a menu or the panel is tracking.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        isRunning = false
        timer?.invalidate()
        timer = nil
    }

    /// Call straight after writing to the pasteboard ourselves, so pasting an
    /// item does not immediately re-capture it as a brand new entry.
    public func acknowledgeOwnWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Polling

    /// Drives one polling tick synchronously, so tests do not depend on timing.
    func pollForTesting() {
        poll()
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if let item = readCurrentContents() {
            onCapture?(item)
        }
    }

    /// Reads the richest representation available, preferring image over rich
    /// text over plain text — apps often offer several at once.
    func readCurrentContents() -> ClipboardItem? {
        guard let types = pasteboard.types else { return nil }
        guard !types.contains(where: { Self.excludedTypes.contains($0.rawValue) }) else { return nil }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        if let item = readImage(source: source) { return item }
        if let item = readRichText(source: source) { return item }
        return readPlainText(source: source)
    }

    private func readImage(source: String?) -> ClipboardItem? {
        let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
        guard let data,
              let image = NSImage(data: data),
              let png = image.pngRepresentation
        else { return nil }

        // Without somewhere to store the bytes an image entry cannot be
        // rebuilt later, so skip rather than record a dangling row.
        guard let persistence, let filename = try? persistence.saveImage(png) else { return nil }

        let size = image.pixelSize
        return .image(
            filename: filename,
            pngData: png,
            pixelSize: "\(Int(size.width))×\(Int(size.height))",
            sourceBundleID: source
        )
    }

    private func readRichText(source: String?) -> ClipboardItem? {
        guard let rtf = pasteboard.data(forType: .rtf),
              let plain = pasteboard.string(forType: .string),
              !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        return .richText(rtf: rtf, plainText: plain, sourceBundleID: source)
    }

    private func readPlainText(source: String?) -> ClipboardItem? {
        guard let value = pasteboard.string(forType: .string),
              !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        return .text(value, sourceBundleID: source)
    }
}

extension NSImage {
    /// Re-encodes to PNG so every stored image has one predictable format.
    public var pngRepresentation: Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff)
        else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    /// Pixel dimensions, which differ from `size` (points) on Retina displays.
    public var pixelSize: NSSize {
        guard let rep = representations.first else { return size }
        return NSSize(width: rep.pixelsWide, height: rep.pixelsHigh)
    }
}
