import Foundation

/// A named group of insertable glyphs (symbols or kaomoji).
public struct SymbolCategory: Codable, Equatable, Identifiable, Sendable {
    public let name: String
    public let symbols: [String]
    public var id: String { name }
}

public struct Emoji: Codable, Equatable, Identifiable, Sendable {
    public let char: String
    public let name: String
    /// Lower-cased search terms derived from the official Unicode name.
    public let keywords: String
    public var id: String { char }

    // Memberwise inits are internal by default; the app target builds these
    // directly for the "recently used" row.
    public init(char: String, name: String, keywords: String) {
        self.char = char
        self.name = name
        self.keywords = keywords
    }
}

public struct EmojiCategory: Codable, Equatable, Identifiable, Sendable {
    public let name: String
    public let emoji: [Emoji]
    public var id: String { name }
}

/// Static, offline glyph catalogues loaded from the resource bundle.
///
/// `emoji.json` is generated by `scripts/generate-emoji.py`; the others are
/// maintained by hand.
public enum Catalogues {

    public enum LoadError: Error, CustomStringConvertible {
        case missingResource(String)

        public var description: String {
            switch self {
            case .missingResource(let name):
                return "Resource \(name) is missing from the app bundle."
            }
        }
    }

    private struct SymbolFile: Codable { let categories: [SymbolCategory] }
    private struct EmojiFile: Codable { let categories: [EmojiCategory] }

    // Loaded once: these are static data.
    public static let symbols: [SymbolCategory] = (try? loadSymbols()) ?? []
    public static let kaomoji: [SymbolCategory] = (try? loadKaomoji()) ?? []
    public static let emoji: [EmojiCategory] = (try? loadEmoji()) ?? []

    // Throwing variants, so tests can tell "missing" apart from "empty".

    public static func loadSymbols() throws -> [SymbolCategory] {
        try decode(SymbolFile.self, from: "symbols").categories
    }

    public static func loadKaomoji() throws -> [SymbolCategory] {
        try decode(SymbolFile.self, from: "kaomoji").categories
    }

    public static func loadEmoji() throws -> [EmojiCategory] {
        try decode(EmojiFile.self, from: "emoji").categories
    }

    // MARK: - Search

    /// Matches on name and keywords, so "cry" and "sad face" both work.
    public static func searchEmoji(_ query: String) -> [Emoji] {
        let needle = query
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
        guard !needle.isEmpty else { return [] }

        return emoji
            .flatMap(\.emoji)
            .filter { $0.keywords.contains(needle) || $0.name.lowercased().contains(needle) }
    }

    private static func decode<T: Decodable>(_ type: T.Type, from resource: String) throws -> T {
        guard let url = Bundle.module.url(forResource: resource, withExtension: "json") else {
            throw LoadError.missingResource("\(resource).json")
        }
        return try JSONDecoder().decode(type, from: Data(contentsOf: url))
    }
}
